### ISSUE TITLE
How do I connect the VueComponent to the root Vue after class declaration?

### ISSUE THREAD

**Issue by hdavidzhu** [weichx/vue-ts#2]
I am unsure of how to connect VueComponent to Vue after creating the class. I've made a simple VueComponent class following the `README` at the beginning of the page. In my root `index.html`, I am trying:

```
new Vue({ el: '#app' });
import { PodCard } from './components/pod_card/pod_card';
new PodCard();
```

At this point, I have no idea how to register or add the component to the main Vue root. What is the best way to go about this?

**Comment by weichx** [comment]
@VueComponent will register the component for you, all you need to do is use `<pod-card></pod-card>`in your template somewhere

**Comment by hdavidzhu** [comment]
Is this what you mean? 

https://github.com/urbanpod/web_client/compare/master...feature/grid#diff-2d4f7ccd4c26bc3e17589889955dc844R3

My DOM does not get updated. It just stays as `<pod-card></card>`

**Comment by hdavidzhu** [comment]
@weichx Been messing around a bit with the declares, still no luck 😢

**Comment by hdavidzhu** [comment]
Resolved! `vue` needs to be loaded locally as an npm package for the component to be picked up.

**Comment by weichx** [comment]
sweet, sorry for being awol been pretty busy, i had blocked off time to look at this today glad it got figured out

**Comment by hdavidzhu** [comment]
One thing that is weird is that I still have to do `new PodCard()` and then create a `new Vue(...)` right after it. Otherwise `Vue` does not get registered or pick up any components.
